Refactor SOSS core to Integration Service Core and add extensive doxygen documentation
eProsima/Integration-Service pull request #57
Opened 2021-03-18 11:02 UTC by jamoralp

2021-03-24 13:41 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss&build=152)](http://jenkins.eprosima.com:8080/job/soss/152/)

2021-03-25 14:38 UTC, laura-eprosima requested changes
Review Warn and Error logger prints

2021-03-25 14:38 UTC, lauramg15 commented on packages/core/src/Config.cpp
> +                Config::logger << utils::Logger::Level::ERROR
If it is an error, it would return false, if not set the level to warning

2021-03-25 14:38 UTC, lauramg15 commented on packages/core/src/Config.cpp
> +        Config::logger << utils::Logger::Level::WARN
```suggestion
        Config::logger << utils::Logger::Level::ERROR
```

2021-03-25 14:38 UTC, laura-eprosima commented on packages/core/src/Config.cpp
> +        ServiceInfo topic_info_client = remap_if_needed(client, config.remap,
```suggestion
        ServiceInfo client_info = remap_if_needed(client, config.remap,
```

2021-03-25 14:38 UTC, laura-eprosima commented on packages/core/src/Config.cpp
> +        ServiceInfo topic_info_server = remap_if_needed(config.route.server, config.remap,
```suggestion
        ServiceInfo server_info = remap_if_needed(config.route.server, config.remap,
```

2021-03-25 14:38 UTC, laura-eprosima commented on packages/core/src/Instance.cpp
> +                    << "Error: Attemtping to run an Integration Service instance without at least "
```suggestion
                    << "Attemtping to run an Integration Service instance without at least "
```

2021-03-26 14:17 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss&build=171)](http://jenkins.eprosima.com:8080/job/soss/171/)

2021-03-29 05:38 UTC, laura-eprosima approved these changes

2021-03-29 08:59 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss&build=179)](http://jenkins.eprosima.com:8080/job/soss/179/)

2021-03-29 09:03 UTC, jamoralp commented
Closing, branch will be kept until the refactor of the systemhandles is completed

2021-03-29 09:03 UTC, closed without merging

2021-04-06 06:58 UTC, jamoralp commented
TODO:
* Readme.MD file